//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystemCustom/Input Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Input Actions"",
    ""maps"": [
        {
            ""name"": ""Phone"",
            ""id"": ""ac1219ed-a02c-4678-9d87-8466f3869e14"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""a64ee366-fd8f-4342-a8bc-f657c758b3e2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""1df272c2-8f02-497b-9618-fdd02c13b522"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attitude"",
                    ""type"": ""Value"",
                    ""id"": ""da088950-1be8-422d-a02b-d0f23f7837a0"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LinearAcceleration"",
                    ""type"": ""Value"",
                    ""id"": ""b5453b4b-db94-42eb-96c1-486578c13cf3"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Acceleration"",
                    ""type"": ""Value"",
                    ""id"": ""c6a5be75-b523-474e-b8b1-1926b4bd8f80"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""AngVelocity"",
                    ""type"": ""Value"",
                    ""id"": ""7e8ba50d-49a1-435a-943c-b92a54685bb4"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PhonePosition"",
                    ""type"": ""Value"",
                    ""id"": ""9e4923e7-5df7-429d-a284-89c692995873"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PhoneRotation"",
                    ""type"": ""Value"",
                    ""id"": ""6b5b6bc3-ab64-445d-ba22-10b0d4fedaaa"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Clicked"",
                    ""type"": ""Button"",
                    ""id"": ""ff26e90a-de68-45fe-89fa-42fb1e1c664c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveTouch"",
                    ""type"": ""Value"",
                    ""id"": ""850a9125-251b-4535-8bd8-0f1640726178"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrimaryFingerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""00e5089e-278b-4ec6-973b-cb69abfa0365"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondaryFingerPosition"",
                    ""type"": ""Value"",
                    ""id"": ""f8cf64ed-4bf6-4f74-8986-dd092336c6cf"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SecondaryTouchContact"",
                    ""type"": ""Button"",
                    ""id"": ""3f9ecdb2-b0ee-4f8c-a13b-5fc49858bfdf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootAction"",
                    ""type"": ""Value"",
                    ""id"": ""6306c2a9-c538-472e-b23c-a9b8dc0c0c22"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""65055960-6e9a-4502-b3b2-1a75e17b3fba"",
                    ""path"": ""<AttitudeSensor>/attitude"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attitude"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cdd563f2-d436-4c0a-8f0a-b453d633aac1"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34068a5e-aa1a-43dc-a88d-020197052661"",
                    ""path"": ""<LinearAccelerationSensor>/acceleration"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LinearAcceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cee76cdc-2631-4a81-8045-c7dcde866ebc"",
                    ""path"": ""<Accelerometer>/acceleration"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Acceleration"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f55d2ab8-f479-4e81-bbc5-1cd2c8668b8c"",
                    ""path"": ""<Gyroscope>/angularVelocity"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AngVelocity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""594abc7e-9796-42ae-9ede-f01f749d662b"",
                    ""path"": ""<TrackedDevice>/devicePosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PhonePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03940047-4fa6-4e3f-92af-769c55878f1d"",
                    ""path"": ""<TrackedDevice>/deviceRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PhoneRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50b94093-076b-49ef-bef4-e6ccb415298a"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Clicked"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f661e322-af78-43e5-a550-e45199ebdaf7"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cd34752-020c-4cb4-8375-cc60989b2814"",
                    ""path"": ""<Touchscreen>/touch0/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveTouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4607dd4f-4507-4178-a67f-e2621c669df3"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryFingerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2462b18-a711-4551-a29d-c49214ee5ac5"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryFingerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8088f117-8e4e-494d-8395-6174ccb4965a"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SecondaryTouchContact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9a09b83-59dc-444b-a109-99f5aff4211b"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Phone
        m_Phone = asset.FindActionMap("Phone", throwIfNotFound: true);
        m_Phone_Move = m_Phone.FindAction("Move", throwIfNotFound: true);
        m_Phone_Jump = m_Phone.FindAction("Jump", throwIfNotFound: true);
        m_Phone_Attitude = m_Phone.FindAction("Attitude", throwIfNotFound: true);
        m_Phone_LinearAcceleration = m_Phone.FindAction("LinearAcceleration", throwIfNotFound: true);
        m_Phone_Acceleration = m_Phone.FindAction("Acceleration", throwIfNotFound: true);
        m_Phone_AngVelocity = m_Phone.FindAction("AngVelocity", throwIfNotFound: true);
        m_Phone_PhonePosition = m_Phone.FindAction("PhonePosition", throwIfNotFound: true);
        m_Phone_PhoneRotation = m_Phone.FindAction("PhoneRotation", throwIfNotFound: true);
        m_Phone_Clicked = m_Phone.FindAction("Clicked", throwIfNotFound: true);
        m_Phone_MoveTouch = m_Phone.FindAction("MoveTouch", throwIfNotFound: true);
        m_Phone_PrimaryFingerPosition = m_Phone.FindAction("PrimaryFingerPosition", throwIfNotFound: true);
        m_Phone_SecondaryFingerPosition = m_Phone.FindAction("SecondaryFingerPosition", throwIfNotFound: true);
        m_Phone_SecondaryTouchContact = m_Phone.FindAction("SecondaryTouchContact", throwIfNotFound: true);
        m_Phone_ShootAction = m_Phone.FindAction("ShootAction", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Phone
    private readonly InputActionMap m_Phone;
    private List<IPhoneActions> m_PhoneActionsCallbackInterfaces = new List<IPhoneActions>();
    private readonly InputAction m_Phone_Move;
    private readonly InputAction m_Phone_Jump;
    private readonly InputAction m_Phone_Attitude;
    private readonly InputAction m_Phone_LinearAcceleration;
    private readonly InputAction m_Phone_Acceleration;
    private readonly InputAction m_Phone_AngVelocity;
    private readonly InputAction m_Phone_PhonePosition;
    private readonly InputAction m_Phone_PhoneRotation;
    private readonly InputAction m_Phone_Clicked;
    private readonly InputAction m_Phone_MoveTouch;
    private readonly InputAction m_Phone_PrimaryFingerPosition;
    private readonly InputAction m_Phone_SecondaryFingerPosition;
    private readonly InputAction m_Phone_SecondaryTouchContact;
    private readonly InputAction m_Phone_ShootAction;
    public struct PhoneActions
    {
        private @InputActions m_Wrapper;
        public PhoneActions(@InputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Phone_Move;
        public InputAction @Jump => m_Wrapper.m_Phone_Jump;
        public InputAction @Attitude => m_Wrapper.m_Phone_Attitude;
        public InputAction @LinearAcceleration => m_Wrapper.m_Phone_LinearAcceleration;
        public InputAction @Acceleration => m_Wrapper.m_Phone_Acceleration;
        public InputAction @AngVelocity => m_Wrapper.m_Phone_AngVelocity;
        public InputAction @PhonePosition => m_Wrapper.m_Phone_PhonePosition;
        public InputAction @PhoneRotation => m_Wrapper.m_Phone_PhoneRotation;
        public InputAction @Clicked => m_Wrapper.m_Phone_Clicked;
        public InputAction @MoveTouch => m_Wrapper.m_Phone_MoveTouch;
        public InputAction @PrimaryFingerPosition => m_Wrapper.m_Phone_PrimaryFingerPosition;
        public InputAction @SecondaryFingerPosition => m_Wrapper.m_Phone_SecondaryFingerPosition;
        public InputAction @SecondaryTouchContact => m_Wrapper.m_Phone_SecondaryTouchContact;
        public InputAction @ShootAction => m_Wrapper.m_Phone_ShootAction;
        public InputActionMap Get() { return m_Wrapper.m_Phone; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PhoneActions set) { return set.Get(); }
        public void AddCallbacks(IPhoneActions instance)
        {
            if (instance == null || m_Wrapper.m_PhoneActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PhoneActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Attitude.started += instance.OnAttitude;
            @Attitude.performed += instance.OnAttitude;
            @Attitude.canceled += instance.OnAttitude;
            @LinearAcceleration.started += instance.OnLinearAcceleration;
            @LinearAcceleration.performed += instance.OnLinearAcceleration;
            @LinearAcceleration.canceled += instance.OnLinearAcceleration;
            @Acceleration.started += instance.OnAcceleration;
            @Acceleration.performed += instance.OnAcceleration;
            @Acceleration.canceled += instance.OnAcceleration;
            @AngVelocity.started += instance.OnAngVelocity;
            @AngVelocity.performed += instance.OnAngVelocity;
            @AngVelocity.canceled += instance.OnAngVelocity;
            @PhonePosition.started += instance.OnPhonePosition;
            @PhonePosition.performed += instance.OnPhonePosition;
            @PhonePosition.canceled += instance.OnPhonePosition;
            @PhoneRotation.started += instance.OnPhoneRotation;
            @PhoneRotation.performed += instance.OnPhoneRotation;
            @PhoneRotation.canceled += instance.OnPhoneRotation;
            @Clicked.started += instance.OnClicked;
            @Clicked.performed += instance.OnClicked;
            @Clicked.canceled += instance.OnClicked;
            @MoveTouch.started += instance.OnMoveTouch;
            @MoveTouch.performed += instance.OnMoveTouch;
            @MoveTouch.canceled += instance.OnMoveTouch;
            @PrimaryFingerPosition.started += instance.OnPrimaryFingerPosition;
            @PrimaryFingerPosition.performed += instance.OnPrimaryFingerPosition;
            @PrimaryFingerPosition.canceled += instance.OnPrimaryFingerPosition;
            @SecondaryFingerPosition.started += instance.OnSecondaryFingerPosition;
            @SecondaryFingerPosition.performed += instance.OnSecondaryFingerPosition;
            @SecondaryFingerPosition.canceled += instance.OnSecondaryFingerPosition;
            @SecondaryTouchContact.started += instance.OnSecondaryTouchContact;
            @SecondaryTouchContact.performed += instance.OnSecondaryTouchContact;
            @SecondaryTouchContact.canceled += instance.OnSecondaryTouchContact;
            @ShootAction.started += instance.OnShootAction;
            @ShootAction.performed += instance.OnShootAction;
            @ShootAction.canceled += instance.OnShootAction;
        }

        private void UnregisterCallbacks(IPhoneActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Attitude.started -= instance.OnAttitude;
            @Attitude.performed -= instance.OnAttitude;
            @Attitude.canceled -= instance.OnAttitude;
            @LinearAcceleration.started -= instance.OnLinearAcceleration;
            @LinearAcceleration.performed -= instance.OnLinearAcceleration;
            @LinearAcceleration.canceled -= instance.OnLinearAcceleration;
            @Acceleration.started -= instance.OnAcceleration;
            @Acceleration.performed -= instance.OnAcceleration;
            @Acceleration.canceled -= instance.OnAcceleration;
            @AngVelocity.started -= instance.OnAngVelocity;
            @AngVelocity.performed -= instance.OnAngVelocity;
            @AngVelocity.canceled -= instance.OnAngVelocity;
            @PhonePosition.started -= instance.OnPhonePosition;
            @PhonePosition.performed -= instance.OnPhonePosition;
            @PhonePosition.canceled -= instance.OnPhonePosition;
            @PhoneRotation.started -= instance.OnPhoneRotation;
            @PhoneRotation.performed -= instance.OnPhoneRotation;
            @PhoneRotation.canceled -= instance.OnPhoneRotation;
            @Clicked.started -= instance.OnClicked;
            @Clicked.performed -= instance.OnClicked;
            @Clicked.canceled -= instance.OnClicked;
            @MoveTouch.started -= instance.OnMoveTouch;
            @MoveTouch.performed -= instance.OnMoveTouch;
            @MoveTouch.canceled -= instance.OnMoveTouch;
            @PrimaryFingerPosition.started -= instance.OnPrimaryFingerPosition;
            @PrimaryFingerPosition.performed -= instance.OnPrimaryFingerPosition;
            @PrimaryFingerPosition.canceled -= instance.OnPrimaryFingerPosition;
            @SecondaryFingerPosition.started -= instance.OnSecondaryFingerPosition;
            @SecondaryFingerPosition.performed -= instance.OnSecondaryFingerPosition;
            @SecondaryFingerPosition.canceled -= instance.OnSecondaryFingerPosition;
            @SecondaryTouchContact.started -= instance.OnSecondaryTouchContact;
            @SecondaryTouchContact.performed -= instance.OnSecondaryTouchContact;
            @SecondaryTouchContact.canceled -= instance.OnSecondaryTouchContact;
            @ShootAction.started -= instance.OnShootAction;
            @ShootAction.performed -= instance.OnShootAction;
            @ShootAction.canceled -= instance.OnShootAction;
        }

        public void RemoveCallbacks(IPhoneActions instance)
        {
            if (m_Wrapper.m_PhoneActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPhoneActions instance)
        {
            foreach (var item in m_Wrapper.m_PhoneActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PhoneActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PhoneActions @Phone => new PhoneActions(this);
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPhoneActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnAttitude(InputAction.CallbackContext context);
        void OnLinearAcceleration(InputAction.CallbackContext context);
        void OnAcceleration(InputAction.CallbackContext context);
        void OnAngVelocity(InputAction.CallbackContext context);
        void OnPhonePosition(InputAction.CallbackContext context);
        void OnPhoneRotation(InputAction.CallbackContext context);
        void OnClicked(InputAction.CallbackContext context);
        void OnMoveTouch(InputAction.CallbackContext context);
        void OnPrimaryFingerPosition(InputAction.CallbackContext context);
        void OnSecondaryFingerPosition(InputAction.CallbackContext context);
        void OnSecondaryTouchContact(InputAction.CallbackContext context);
        void OnShootAction(InputAction.CallbackContext context);
    }
}
